version: '1'
services:
  financial_data_app:
    container_name: finanical_data
    image: assignment/financial_data:1.0.0
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_db:5432/${POSTGRES_DB}
    depends_on:
      - postgres_db
  postgres_db:
    container_name: postgres_db
    hostname: localhost
    image: postgres:latest
    ports:
      - "5432:5432"
#    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data